# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='raw_address',
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, help_text='The full address if the form does not apply for your address.', max_length=200),
        ),
    ]
