# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190329_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='applicationstatuslink',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='companyrating',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-order', 'text', 'url']},
        ),
        migrations.AlterModelOptions(
            name='positionlocation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
