# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190401_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'get_latest_by': ['order', 'date', 'created_at'], 'ordering': ['created_at'], 'verbose_name_plural': 'application_statuses'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, help_text='The full address of the form does not apply for your address.', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Application'),
        ),
    ]
