# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190406_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatuslink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='The date this status is updated. You can modify this field to reflect the correct date, especially when you create this status at a later point.', null=True),
        ),
    ]
