# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190413_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatuslink',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Link'),
        ),
    ]
