# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190413_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
