# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190414_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='The date this status is updated. You can modify this field to reflect the correct date, especially when you create this status at a later point.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
