# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190420_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=500),
        ),
    ]
