# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190516_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(blank=True, default='Link', max_length=200),
        ),
    ]
