# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190516_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
