# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-17 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_application_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-modified_at', '-created_at'), 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-modified_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'get_latest_by': ['order', 'date', 'created_at'], 'ordering': ('-modified_at', '-created_at'), 'verbose_name_plural': 'application_statuses'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatuslink',
            options={'ordering': ('-modified_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-modified_at', '-created_at'), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companyrating',
            options={'ordering': ('-modified_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='positionlocation',
            options={'ordering': ('-modified_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='application',
            name='job_description_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
